language: ruby
rvm:
  - 2.4.1
sudo: required
cache: bundler
install:
  - bundle install
  - sudo pip install awscli
script:
  - bundle exec middleman build -e production
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: pidapalooza.org
  local-dir: build
  skip_cleanup: true
  region: eu-west-1
  detect_encoding: true
  on:
    branch: master
after_deploy:
  - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY
  - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY
  # Allow `awscli` to make requests to CloudFront.
  - aws configure set preview.cloudfront true
  # Invalidate every object in the targeted distribution.
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
notifications:
  slack: datacite:Wt8En0ALoTA6Kjc5EOKNDWxN
  email: false
